// Mocks generated by Mockito 5.0.14 from annotations
// in flutter_news_test_bloc/test/features/news/data/repositories/news_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:flutter_news_test_bloc/core/network/connection/network_info.dart'
    as _i7;
import 'package:flutter_news_test_bloc/features/news/data/datasources/news_remote_data_source.dart'
    as _i5;
import 'package:flutter_news_test_bloc/features/news/data/models/news_response_model.dart'
    as _i3;
import 'package:http/http.dart' as _i2;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

class _FakeNewsResponseModel_1 extends _i1.Fake
    implements _i3.NewsResponseModel {}

class _FakeInternetConnectionChecker_2 extends _i1.Fake
    implements _i4.InternetConnectionChecker {}

/// A class which mocks [NewsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRemoteDataSource extends _i1.Mock
    implements _i5.NewsRemoteDataSource {
  MockNewsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i6.Future<_i3.NewsResponseModel> getNews() => (super.noSuchMethod(
          Invocation.method(#getNews, []),
          returnValue:
              Future<_i3.NewsResponseModel>.value(_FakeNewsResponseModel_1()))
      as _i6.Future<_i3.NewsResponseModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.InternetConnectionChecker get internetConnection =>
      (super.noSuchMethod(Invocation.getter(#internetConnection),
              returnValue: _FakeInternetConnectionChecker_2())
          as _i4.InternetConnectionChecker);
  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  String toString() => super.toString();
}
